### ISSUE TITLE
Add support for Noir as frontend

### ISSUE THREAD

**Issue by Savio-Sou** [privacy-scaling-explorations/sonobe#124]
Add to sonobe the ability to parse Noir (more accurately ACIR, Noir's intermediate representation of choice) and specifically its folding opcode; hence the ability to fold, prove and generate verifiers for circuits written in Noir.

Relevant links:
- Noir repo: https://github.com/noir-lang/noir
- ACIR folder: https://github.com/noir-lang/noir/tree/master/acvm-repo
- Reference Noir --> proving backend (e.g. `bb`) workflow: https://noir-lang.org/docs/dev/getting_started/hello_noir/
- Noir PR adding `#[fold]` attribute: https://github.com/AztecProtocol/aztec-packages/pull/5341
- Barretenberg PR adding ability to fold ACIR: https://github.com/AztecProtocol/aztec-packages/pull/6563

**Comment by dmpierre** [comment]
Hey, thanks for suggesting this, we would indeed like to tackle this. Let me have a look!

**Comment by dmpierre** [comment]
(small update: waiting for the aztec noir team to circle back on a few questions)

**Comment by Savio-Sou** [comment]
Additional reference: Closest pointer to ACIR --> R1CS would be [arkworks_bridge](https://github.com/noir-lang/arkworks_backend/blob/master/src/bridge.rs), which does conversion of ACIR opcodes but to a new data structure instead of R1CS (like in the `circom_compat` struct).

Note that conversion is incomplete, where only `AssertZero` ACIR opcodes are handled as they can be converted into R1CS cleanly, while other opcodes would fail.

A possible approach could be building a converter which:
1. Decomposes every ACIR opcode into `AssertZero` opcodes (a la `acvm_stdlib`)
2. Uses ACVM to perform witness generation on this ACIR
3. Converts this ACIR into R1CS

Follows by witness generation, which can either be witness generation on the ACIR or custom witness generation on the R1CS output.

(Credit @TomAFrench for insights)

**Comment by dmpierre** [comment]
It seems like this approach is [working](https://github.com/dmpierre/arkworks_backend/blob/192e5b9330c8f950e0b047912b18c374159b99d7/src/lib.rs#L104). With a few modifications, I managed to test it for a circuit with a shape similar to what sonobe expects. I will work on integrating this modified version of the `arkworks_bridge` into the lib now!
