### ISSUE TITLE
Implement Nova folding fitting into `FoldingScheme` trait

### ISSUE THREAD

**Issue by arnaucube** [privacy-scaling-explorations/sonobe#24]
Depends on #18 and #23 .
Once AugmentedF circuit (#18 ) and proving step ( #23 ) are ready, implement the full folding fitting into the [Folding Scheme trait](https://github.com/privacy-scaling-explorations/folding-schemes/blob/d9887af5352ad4d51d1db049a8f0eb4019f47905/src/lib.rs#L29).

**Comment by ameya-deshmukh** [comment]
@arnaucube is this still open to take up?

**Comment by arnaucube** [comment]
Hi, this issue depends on #18 & #23, which are not yet done.
Currently I'm working on #18, and was planning to continue on #23 and this one (#24) since are all kind of the same consecutive track, but if you want to work on this one we can coordinate once #18 & #23 are ready.

**Comment by arnaucube** [comment]
Closing, as it was done across the PRs #33, #36, #45, #63, #64.
