### ISSUE TITLE
Solidity pedersen verifier

### ISSUE THREAD

**Issue by arnaucube** [privacy-scaling-explorations/sonobe#25]
For the Decider proof, we will have a SNARK proof proving the circuit from https://github.com/privacy-scaling-explorations/folding-schemes/issues/19 / https://github.com/privacy-scaling-explorations/folding-schemes/pull/21 , which checks the RelaxedR1CS relation, but does not check the openings of `cm(E)` and `cm(W)` since it would be too expensive in terms of constraints (although still doable).
One approach to explore, is if since we use CycleFold, we could just verify those openings directly together when verifying the SNARK proof. So for example, in the verification in Ethereum case, we would have a SNARK proof using Groth16 over the BN254 curve, and then 2 pedersen proofs which are also over the BN254, thus the Solidity verifier would verify the 3 proofs (1 Groth16 + 2 pedersen proofs (all over BN254)).
We need to see how feasible is this approach on the theoretical side, but also on the practical side in terms of gas costs.

**Comment by chokermaxx** [comment]
I wanna work on this, if it's vacant! Seems like a good first issue. Just to confirm:
1. an on-chain contract takes pedersen vector commitments $\bar E$ and $\bar W$, and a Groth16 proof whose circuit takes vectors E and W as public inputs
2. the Groth16 proof is binding to both E and W. resistant to [Malleability Attack](https://geometry.xyz/notebook/groth16-malleability)
3. the contract must verify that pedersen vector commitments $\bar E$ and $\bar Z$ indeed commits to E and W

**Comment by arnaucube** [comment]
> Warning: we are still figuring out the whole system, so not sure if this approach will be feasible at the end, thus this issue is more an exploratory path.

The complete contract would verify 2 things:
1) Groth16 that checks the circuit [`RelaxedR1CSGadget`](https://github.com/privacy-scaling-explorations/folding-schemes/blob/8256c27609a2effbf9a255f0709eb0b1c3055b36/src/decider/circuit.rs#L22). Note that this is a normal R1CS circuit with a normal Groth16 prover, which internally is verifying a RelaxedR1CS relation, but for what Solidity concerns, is just a normal Groth16 for normal R1CS relation proof. So we can reuse the already existing Groth16 proof: https://github.com/arkworks-rs/groth16 .
2) The Pedersen commitment proofs of $\overline{E},~\overline{W}$ for the $E,~W$ used as inputs in the `RelaxedR1CSGadget` circuit.

The current issue defines the point 2), which is the Solidity code that is currently missing.

But be aware that this is still an exploratory path.

**Comment by chokermaxx** [comment]
I've naively implemented a contract that verifies pedersen vector commitment by calling precompiled BN254 ECADD/ECMUL. I came to a conclusion that this approach is not feasable. Lurk, a famous zkVM implemented with Nova, uses roughly 30000 witnesses. So I benchmarked my contract with this number, and it gave me gas consumption of 731675465. With the current rate of 1 gas = 10 gwei, the gas consumption roughly equals to 7ETH. I think the key to optimize this is to avoid use of ECMUL as its gas cost is expensive. I'll next implement pippenger-like algorithm that uses only ECADD and point doubling. Parallelization is not possible in Solidity so I'll ditch that part from the algorithm. I estimate we can reduce the gas cost by 100x this way.

**Comment by chokermaxx** [comment]
or most zkVMs don't use that much witnesses? In that case the naive implementation would be fine. If so I'll make a PR.

**Comment by arnaucube** [comment]
Closing as this was an exploratory issue as mentioned in earlier comments:

> Warning: we are still figuring out the whole system, so not sure if this approach will be feasible at the end, thus this issue is more an exploratory path.

and we ended up solving it through a different approach, described at https://privacy-scaling-explorations.github.io/sonobe-docs/design/nova-decider-onchain.html .
Nonetheless, thanks @chokermaxx for exploring the gas costs of doing the pedersen verifications in solidity!
