### ISSUE TITLE
HyperNova NIMFS verifier circuit

### ISSUE THREAD

**Issue by arnaucube** [privacy-scaling-explorations/sonobe#50]
Depends on https://github.com/privacy-scaling-explorations/folding-schemes/issues/13

Reference: section 5 of HyperNova paper: https://eprint.iacr.org/2023/573.pdf

**Comment by dmpierre** [comment]
[This PR](https://github.com/privacy-scaling-explorations/folding-schemes/pull/61) creates an R1CS gadget for computing $c$, as laid out in section 5, step 5.
