### ISSUE TITLE
Update the `frontend/circom` into fit the `FCircuit` trait

### ISSUE THREAD

**Issue by arnaucube** [privacy-scaling-explorations/sonobe#55]
Update the [`frontend/circom`](https://github.com/privacy-scaling-explorations/folding-schemes/blob/498198057b78224e4ec9f92be077b2c873b5e894/src/frontend/circom/mod.rs) to adapt it to fit into the [`FCircuit` trait](https://github.com/privacy-scaling-explorations/folding-schemes/blob/main/src/frontend/mod.rs#L13).

**Comment by arnaucube** [comment]
To have the info (since I can not assign the issue through the GitHub UI), @yugocabrio has signaled interest on this task: https://github.com/privacy-scaling-explorations/folding-schemes/pull/32#issuecomment-1886679937

**Comment by yugocabrio** [comment]
Since #54 has been merged, may I begin this task?

**Comment by arnaucube** [comment]
Yes! That would be great :smile_cat:

**Comment by arnaucube** [comment]
Closing as it was done in #71.
