### ISSUE TITLE
Should `AugmentedFCircuit` for Nova include an additional public input for CycleFold?

### ISSUE THREAD

**Issue by winderica** [privacy-scaling-explorations/sonobe#83]
In `AugmentedFCircuit` for Nova, we currently check:
https://github.com/privacy-scaling-explorations/sonobe/blob/fe9a488f63fd8a131119cd3e40ec4d80dcf4690a/folding-schemes/src/folding/nova/circuits.rs#L486-L503
1. `cf1_U_i1` is correctly folded from `cf_U_i` and `cf1_u_i`, and
2. `cf_U_i1` is correctly folded from `cf1_U_i1` and `cf2_u_i`.

However, these checks are insufficient to ensure that `cf_U_i1` is indeed the result from the CycleFold circuit, as `cf_U_i1` is a witness rather than a public input.

Being curious about this, I looked into [arecibo](https://github.com/lurk-lab/arecibo)'s implementation, where the correctness of folding `U_c` (our `cf_U_i1`) is also checked in the [circuit](https://github.com/lurk-lab/arecibo/blob/5268c2084821955c5953c29c7e179b2052523b5d/src/cyclefold/nova_circuit.rs#L372-L379), but the circuit further computes `hash_c`, [the digest of `U_c`](https://github.com/lurk-lab/arecibo/blob/5268c2084821955c5953c29c7e179b2052523b5d/src/cyclefold/nova_circuit.rs#L500-L510) (`Unew_c` in the referred code is equal to `U_c` in non-base cases), which is [treated the second public input to the circuit](https://github.com/lurk-lab/arecibo/blob/5268c2084821955c5953c29c7e179b2052523b5d/src/cyclefold/nova_circuit.rs#L513). I think this makes more sense as it allows one to verify if the in-circuit variable `cf_U_i1` is indeed the desired one.

Btw, [this hackmd](https://hackmd.io/SBvAur_2RQmaduDi7gYbhw) explains arecibo's implementation in detail, and it also mentions that "The Nova augmented circuit has a public IO vector x of length 2".

Therefore, I guess we should also add another public input to `AugmentedFCircuit` for full soundness, as well as the logic for computing `cf_U_i1`'s digest inside and outside the circuit.

Please correct me if I misunderstood something :)

**Comment by arnaucube** [comment]
Absolutely! I think that you're right, thanks for caring about this! :raised_hands:
Would you like to open a PR adding the checks?

**Comment by winderica** [comment]
Sure, will give it my best shot!
