### ISSUE TITLE
Poseidon configuration params for Ethereum use case

### ISSUE THREAD

**Issue by arnaucube** [privacy-scaling-explorations/sonobe#85]
Currently the tests that require usage of Poseidon are using the [`poseidon_test_config()`](https://github.com/privacy-scaling-explorations/sonobe/blob/b8db622a08ff7c7d11a0003f8bd9a3a8955649e8/folding-schemes/src/transcript/poseidon.rs#L119) params generator.
We need to have a specific method that offers the `poseidon_config` for the Ethereum use case (over Bn254's scalar field), to be used in non-test use cases that want to use the Ethereum Decider to verify the proofs. Ideally using the same config as in [circomlib](https://github.com/iden3/circomlib/blob/master/circuits/poseidon.circom), [noir-stdlib](https://github.com/noir-lang/noir/pull/768), etc.
And maybe the same for [pasta curves](https://o1-labs.github.io/proof-systems/specs/pasta.html) ([pallas](https://github.com/arkworks-rs/algebra/tree/master/curves/pallas) and [vesta](https://github.com/arkworks-rs/algebra/tree/master/curves/vesta)) scalar fields.

**Comment by arnaucube** [comment]
tagging @ax0 as a knowledgeable person who could do this

**Comment by ashu-t3** [comment]
Hi @arnaucube . 

I am interested in this work. Could I get started on adding the configs from circomlib first for BN254.

**Comment by arnaucube** [comment]
Hi @ashu-t3 thanks for showing interest on this one. @ax0 started this one some time ago but got busy with other stuff, but just asked him and he almost have it locally and should be in a PR over the next days.

But if you're still interested, I'm thinking that a next step once this one is completed would be to do the same for the pasta curves fields, as they are the other main curves that seem that are going to be used apart from the bn254 for the Ethereum case. Would you like to do that one?
